### PR TITLE
Adding temperature dependent properties (arrays).

### LINKED ISSUE #151: materials dictionary in pymadl reader result
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Issuing the following:
```py
from ansys.mapdl import reader as pymapdl.reader
result = pymapdl.reader.read_binary(‘file.rth’)
mats = result.materials
 ```
results in the following materials dictionary after reading in thermal model
```
{'EX': None, 'NUXY': None, 'ALPX': None, 'DENS': None, 'KXX': None, 'C': None}
```
The materials in that model have temperature dependent properties. 

### Steps To Reproduce

See above

### Which Operating System are you using?

_No response_

### Which Python version are you using?

_No response_

### PyMAPDL Report
```
-------------------------------------------------------------------------------


PyMAPDL Software and Environment Report


Packages Requirements
*********************

Core packages
-------------
ansys.mapdl.core    : 0.63.1
numpy               : 1.23.0
appdirs             : 1.4.4
scipy               : 1.8.1
grpc                : Package not found
ansys.api.mapdl.v0  : Package not found
ansys.mapdl.reader  : 0.51.14
google.protobuf     : Package not found

Optional packages
-----------------
matplotlib          : 3.5.2
pyvista             : 0.35.1
pyiges              : 0.2.1
tqdm                : 4.64.0
ansys_corba         : 0.1.1


Ansys Installation
******************
Version   Location
------------------
202       C:\Program Files\ANSYS Inc\v202
211       C:\Program Files\ANSYS Inc\v211
212       C:\Program Files\ANSYS Inc\v212
221       C:\Program Files\ANSYS Inc\v221


Ansys Environment Variables
***************************
ANSYS201_DIR                   C:\Program Files\ANSYS Inc\v201\ANSYS
ANSYS202_DIR                   C:\Program Files\ANSYS Inc\v202\ANSYS
ANSYS211_DIR                   C:\Program Files\ANSYS Inc\v211\ANSYS
ANSYS212_DIR                   C:\Program Files\ANSYS Inc\v212\ANSYS
ANSYS221_DIR                   C:\Program Files\ANSYS Inc\v221\ANSYS
ANSYS222_DIR                   C:\Program Files\ANSYS Inc\v222\ANSYS
ANSYSLIC_DIR                   C:\Program Files\ANSYS Inc\Shared Files\Licensing
ANSYS_SYSDIR                   winx64
AWP_LOCALE201                  en-us
AWP_LOCALE202                  en-us
AWP_LOCALE211                  en-us
AWP_LOCALE212                  en-us
AWP_LOCALE221                  en-us
AWP_LOCALE222                  en-us
AWP_ROOT201                    C:\Program Files\ANSYS Inc\v201
AWP_ROOT202                    C:\Program Files\ANSYS Inc\v202
AWP_ROOT211                    C:\Program Files\ANSYS Inc\v211
AWP_ROOT212                    C:\Program Files\ANSYS Inc\v212
AWP_ROOT221                    C:\Program Files\ANSYS Inc\v221
AWP_ROOT222                    C:\Program Files\ANSYS Inc\v222
CADOE_LIBDIR201                C:\Program Files\ANSYS Inc\v201\CommonFiles\Language\en-us
CADOE_LIBDIR202                C:\Program Files\ANSYS Inc\v202\CommonFiles\Language\en-us
CADOE_LIBDIR211                C:\Program Files\ANSYS Inc\v211\CommonFiles\Language\en-us
CADOE_LIBDIR212                C:\Program Files\ANSYS Inc\v212\CommonFiles\Language\en-us
CADOE_LIBDIR221                C:\Program Files\ANSYS Inc\v221\CommonFiles\Language\en-us
CADOE_LIBDIR222                C:\Program Files\ANSYS Inc\v222\CommonFiles\Language\en-us
```

### Installed packages
```
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
ansys-api-mapdl==0.5.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-corba==0.1.1
ansys-dpf-core==0.4.2
ansys-dpf-post==0.2.2
ansys-grpc-dpf==0.4.0
ansys-mapdl-core==0.63.1
ansys-mapdl-reader==0.51.14
ansys-platform-instancemanagement==1.0.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.2
astroid==2.11.6
asttokens==2.0.5
async-timeout==4.0.2
atomicwrites==1.4.1
attrs==21.4.0
autobahn==22.6.1
Automat==20.2.0
autopep8==1.6.0
Babel==2.10.3
backcall==0.2.0
bcrypt==3.2.2
beautifulsoup4==4.11.1
binaryornot==0.4.4
black==22.6.0
bleach==5.0.1
cachetools==5.2.0
certifi==2022.6.15
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.1.0
click==8.1.3
cloudpickle==2.1.0
colorama==0.4.5
constantly==15.1.0
cookiecutter==2.1.1
cryptography==37.0.4
cycler==0.11.0
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
diff-match-patch==20200713
dill==0.3.5.1
docutils==0.18.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
flake8==4.0.1
fonttools==4.34.4
frozenlist==1.3.0
geomdl==5.3.1
google-api-core==2.8.2
google-api-python-client==2.52.0
google-auth==2.9.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.3
grpcio==1.47.0
httplib2==0.20.4
hyperlink==21.0.0
idna==3.3
imageio==2.19.3
imagesize==1.4.1
importlib-metadata==4.12.0
importlib-resources==5.8.0
incremental==21.3.0
inflection==0.5.1
intervaltree==3.1.0
ipykernel==6.15.1
ipython==7.34.0
ipython-genutils==0.2.0
ipywidgets==7.7.1
isort==5.10.1
jedi==0.18.1
jellyfish==0.9.0
Jinja2==3.1.2
jinja2-time==0.2.0
jsonschema==4.6.2
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.1
keyring==23.6.0
kiwisolver==1.4.3
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
multidict==6.0.2
mypy-extensions==0.4.3
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook==6.4.12
numpy==1.23.0
numpydoc==1.4.0
packaging==21.3
pandocfilters==1.5.0
paramiko==2.11.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.5.2
pluggy==1.0.0
progressbar2==4.0.0
prometheus-client==0.14.1
prompt-toolkit==3.0.30
protobuf==3.20.0
protoc-gen-swagger==0.1.0
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycparser==2.21
pydocstyle==6.1.1
pyflakes==2.4.0
Pygments==2.12.0
pyiges==0.2.1
pylint==2.14.4
pyls-spyder==0.4.0
PyNaCl==1.5.0
pyparsing==3.0.9
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
pyrsistent==0.18.1
python-dateutil==2.8.2
python-lsp-black==1.2.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.4.1
python-slugify==6.1.2
python-utils==3.3.3
pytoolconfig==1.2.1
pytz==2022.1
pyvista==0.35.1
pywin32==304
pywin32-ctypes==0.2.0
pywinpty==2.0.6
PyYAML==6.0
pyzmq==23.2.0
QDarkStyle==3.0.3
qstylizer==0.2.1
QtAwesome==1.1.1
qtconsole==5.3.1
QtPy==2.1.0
requests==2.28.1
rope==1.2.0
rsa==4.8
Rtree==1.0.0
scipy==1.8.1
scooby==0.5.12
Send2Trash==1.8.0
six==1.16.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
Sphinx==5.0.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spyder==5.3.1
spyder-kernels==2.3.2
stack-data==0.3.0
style==1.1.0
terminado==0.15.0
text-unidecode==1.3
textdistance==4.3.0
three-merge==0.1.1
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.1
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
Twisted==22.4.0
twisted-iocpsupport==1.0.2
txaio==22.2.1
typing_extensions==4.3.0
ujson==5.4.0
update==0.0.1
uritemplate==4.1.1
urllib3==1.26.10
vtk==9.0.3
watchdog==2.1.9
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.6.1
wrapt==1.14.1
wslink==1.6.6
yapf==0.32.0
yarl==1.7.2
zipp==3.8.0
zope.interface==5.4.0
```

### PR DESCRIPTION
**Pull request by germa89**
As the title.

Close #151

### CODE REVIEW

**Comment by akaszynski** [comment]
Let's add a test for this.

**Review by akaszynski — APPROVED** [review]
LGTM. Good tests and thanks for the validation in #151.

**Comment by akaszynski** [comment]
@germa89, please make a minor release. This seems to be a needed feature.

**Comment by germa89** [comment]
> @germa89, please make a minor release. This seems to be a needed feature.

Done. https://github.com/pyansys/pymapdl-reader/releases/tag/v0.52.0

**Pull request merged**
