### PR TITLE
vtk parse in mesh import can be switched off

### PR DESCRIPTION
**Pull request by NDfp**
added flag to (optionally) exclude the vtk parse when importing the mesh.

Background: on large model, the parsing take a considerable amount of time. If no plotting of the model is desired, the parsing is unnecessary.

### CODE REVIEW

**Comment by akaszynski** [comment]
Sorry for the late review! I've been on vacation and I'm behind on PR reviews.

**Comment by NDfp** [comment]
HI Alex,
no problem.
I am a bit surprised by the error message. It seems the test failed while interpreting the mac version while building the wheel. I haven't however modified that part of the code.  Could it be that the issue is in the base version and not in my modification?

**Comment by akaszynski** [comment]
> Could it be that the issue is in the base version and not in my modification?

It's indeed an issue with the main branch.

---

I've made some final changes to the docstrings, but otherwise this is good to go.

Thanks for your work!

**Review by akaszynski — APPROVED** [review]
Checks pass. Thanks!

Ping me for a release if you need one shortly.

**Comment by NDfp** [comment]
Great. Thank you

**Pull request merged**
