### PR TITLE
Changing deprecated PyVista function

### LINKED ISSUE #209: Deprecated PyVista function (`parse_color`)
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Use of a deprecated pyvista function (`parse_color`) in `_plot_point_scalars` .
It has been located in a  [PyMAPDL PR](https://github.com/pyansys/pymapdl/actions/runs/4114631769/jobs/7102277829#:~:text=392-,File%20%22/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site%2Dpackages/ansys,AttributeError%3A%20module%20%27pyvista%27%20has%20no%20attribute%20%27parse_color%27,-395).

### 📝 Steps to reproduce

Call `_plot_point_scalars` with `text_color != None`.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
*
```

### PR DESCRIPTION
**Pull request by clatapie**
Closes #209.

### CODE REVIEW

**Comment by clatapie** [comment]
The `rst.py` file seems to have more deprecated PyVista functions that initially expected. For example, [plotter.camera_position](https://github.com/pyansys/pymapdl-reader/pull/211/files#:~:text=if%20cpos%3A,camera_position%20%3D%20cpos) is not documented in the PyVista documentation. 
I ping @AlejandroFernandezLuces to get his opinion on it.

**Review by AlejandroFernandezLuces — CHANGES_REQUESTED** [review]
Your changes look fine, but reviewing the whole file I've found some functions that are not using the appropiate methods. I'll point out the methods I find that I think can be substituted by better options

**Comment by AlejandroFernandezLuces** [comment]
I think we can change `plotter.textActor.SetText` for `plotter.add_text` in this occurrences:
https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3122-L3128

https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3337

**Comment by AlejandroFernandezLuces** [comment]
Same with NaN color, I would use the `theme`
https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3044
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.themes.DefaultTheme.nan_color.html#pyvista.themes.DefaultTheme.nan_color

**Comment by AlejandroFernandezLuces** [comment]
> The `rst.py` file seems to have more deprecated PyVista functions that initially expected. For example, [plotter.camera_position](https://github.com/pyansys/pymapdl-reader/pull/211/files#:~:text=if%20cpos%3A,camera_position%20%3D%20cpos) is not documented in the PyVista documentation. I ping @AlejandroFernandezLuces to get his opinion on it.

`camera_position` is documented in PyVista docs, maybe you didn't find it because it is in `BasePlotter`, from which `Plotter` inherits:
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.BasePlotter.camera_position.html#camera-position

FYI, the planar views and the isometric view are implemented in PyVista, just in case you are modifying manually the camera position for this.

**Comment by AlejandroFernandezLuces** [comment]
Remove commented out code:

https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3272-L3274

**Comment by AlejandroFernandezLuces** [comment]
Same as before, use `theme` if possible:

https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3287

**Comment by AlejandroFernandezLuces** [comment]
Substitute for `plotter.add_text` if possible

https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L3335-L3337

**Comment by RobPasMue** [comment]
> Isn't there a [pymapdl@ansys.com](mailto:pymapdl@ansys.com) email or something alike? Maybe we should remove @akaszynski email from here 😄
> 
> https://github.com/pyansys/pymapdl-reader/blob/cdc665de56bedf659911e29874c396e7b3a97cdd/ansys/mapdl/reader/rst.py#L62-L65

Use pyansys.support@ansys.com

**Review by AlejandroFernandezLuces — APPROVED** [review]
LGTM

**Comment by germa89** [comment]
Thank you guys... I'm going to do a release then.

**Comment by RobPasMue** [comment]
Wait @germa89 - I wanted to do it with @clatapie - that way she'll get acquainted with the process. If it's fine with you.

**Comment by germa89** [comment]
I actually thought the same.... but I didn't want to bother you with something I promised I will show her.

Anyways, it is late... @akaszynski already did it..... https://github.com/pyansys/pymapdl-reader/releases/tag/v0.52.9

**Comment by RobPasMue** [comment]
Weird... there is no GitHub release...

**Comment by germa89** [comment]
Yeah... the CICD failed. I'm rerunning

**Comment by RobPasMue** [comment]
Okay, got it. Thanks @germa89!

**Comment by germa89** [comment]
My pleasure #WorkingEarly #FromFar hahaha

**Comment by germa89** [comment]
Running...

https://github.com/pyansys/pymapdl-reader/actions/runs/4130028967

**Comment by germa89** [comment]
I believe this line:

https://github.com/pyansys/pymapdl-reader/blob/main/setup.py#L105

Should be updated?... Because earlier versions of PyVista won't work with this new release?? @RobPasMue @clatapie @AlejandroFernandezLuces

**Comment by AlejandroFernandezLuces** [comment]
> I believe this line:
> 
> https://github.com/pyansys/pymapdl-reader/blob/main/setup.py#L105
> 
> Should be updated?... Because earlier versions of PyVista won't work with this new release?? @RobPasMue @clatapie @AlejandroFernandezLuces

Definetly yes, `parse_color` was removed in 0.38.0. I would go for 0.38.1 as minimum dependency, as there were some bugs fixed in that version.

**Pull request merged**
